# Generated by Django 5.0.6 on 2024-08-13 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.AddField(
            model_name="lecturer",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sector",
                to="portal.department",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="syllabus",
                to="portal.department",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="study",
                to="portal.course",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sector",
                to="portal.faculty",
            ),
        ),
    ]
