# Generated by Django 5.0.6 on 2024-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="lecturer",
            field=models.ManyToManyField(
                null=True, related_name="professor", to="portal.lecturer"
            ),
        ),
    ]
