# Generated by Django 5.0.6 on 2024-08-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "Student"),
                    ("LECTURER", "Lecturer"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="HR",
        ),
    ]
