# Generated by Django 5.0.6 on 2024-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("STUDENT", "Student"),
                    ("LECTURER", "Lecturer"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
