# Generated by Django 5.0.6 on 2024-08-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_unit_lecturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="student",
            field=models.ManyToManyField(
                null=True, related_name="apprentice", to="portal.student"
            ),
        ),
    ]
