# Generated by Django 5.0.6 on 2024-08-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_remove_user_department_lecturer_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
