# Generated by Django 5.0.6 on 2024-08-08 02:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lecturer",
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("portal.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
