# Generated by Django 5.0.6 on 2024-08-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_user_role_delete_hr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit_code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
