# Generated by Django 5.0.6 on 2024-08-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_unit_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="course",
            field=models.ManyToManyField(
                null=True, related_name="program", to="portal.course"
            ),
        ),
    ]
