# Generated by Django 5.0.6 on 2024-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_unit_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="course",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="student",
        ),
        migrations.AddField(
            model_name="course",
            name="units",
            field=models.ManyToManyField(
                null=True, related_name="program", to="portal.unit"
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="units",
            field=models.ManyToManyField(
                null=True, related_name="professor", to="portal.unit"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="units",
            field=models.ManyToManyField(
                null=True, related_name="apprentice", to="portal.unit"
            ),
        ),
    ]
