# Generated by Django 5.0.6 on 2024-08-08 02:45

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="student",
            managers=[
                ("student", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
