# Generated by Django 5.0.6 on 2024-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_remove_unit_course_remove_unit_lecturer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="units",
        ),
        migrations.AddField(
            model_name="unit",
            name="course",
            field=models.ManyToManyField(
                null=True, related_name="topics", to="portal.course"
            ),
        ),
    ]
