# Generated by Django 5.0.6 on 2024-08-08 02:49

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_alter_student_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="admin",
            managers=[
                ("admin", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="hr",
            managers=[
                ("hr", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
