# Generated by Django 5.0.6 on 2024-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_remove_course_units_unit_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_code",
            field=models.CharField(max_length=20),
        ),
    ]
