# Generated by Django 5.0.6 on 2024-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_delete_lecturer_lecturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
