# Generated by Django 5.0.6 on 2024-08-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_unit_unit_alter_unit_unit_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="office",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="units",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="professor", to="portal.unit"
            ),
        ),
    ]
