# Generated by Django 5.0.6 on 2024-08-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_student_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student"},
        ),
    ]
