# Generated by Django 5.0.6 on 2024-08-19 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_alter_lecturer_office_alter_lecturer_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostel",
                    models.CharField(
                        choices=[
                            ("MARINGO", "Maringo"),
                            ("BURUBURU", "BuruBuru"),
                            ("NON_RESIDENT", "Resident"),
                            ("OLD_HALL", "Old Hall"),
                            ("CBD", "CBD"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("room", models.IntegerField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="residence",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tenant",
                to="portal.accomodation",
            ),
        ),
    ]
