# Generated by Django 5.0.6 on 2024-08-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={"verbose_name": "Admin"},
        ),
        migrations.AlterModelOptions(
            name="hr",
            options={"verbose_name": "HR"},
        ),
        migrations.AlterModelOptions(
            name="lecturer",
            options={"verbose_name": "Lecturer"},
        ),
    ]
