# Generated by Django 5.0.6 on 2024-08-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_accomodation_alter_student_residence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Residence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostel",
                    models.CharField(
                        choices=[
                            ("MARINGO", "Maringo"),
                            ("BURUBURU", "BuruBuru"),
                            ("NON_RESIDENT", "Resident"),
                            ("OLD_HALL", "Old Hall"),
                            ("CBD", "CBD"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="accomodation",
            name="hostel",
        ),
        migrations.AddField(
            model_name="accomodation",
            name="bed",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="accomodation",
            name="room",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="residence",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tenant",
                to="portal.accomodation",
            ),
        ),
        migrations.AddField(
            model_name="accomodation",
            name="house",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dorm",
                to="portal.residence",
            ),
        ),
    ]
