# Generated by Django 5.0.6 on 2024-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_residence_remove_accomodation_hostel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residence",
            name="hostel",
            field=models.CharField(
                choices=[
                    ("MARINGO", "Maringo"),
                    ("BURUBURU", "BuruBuru"),
                    ("NON_RESIDENT", "Non Resident"),
                    ("OLD_HALL", "Old Hall"),
                    ("CBD", "CBD"),
                    ("THORNTON", "Thornton"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
