# Generated by Django 5.0.6 on 2024-08-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_alter_admin_options_alter_hr_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
