# Generated by Django 5.0.6 on 2024-08-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_delete_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="office",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="residence",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
