# Generated by Django 5.0.6 on 2024-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_alter_residence_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="is_hod",
            field=models.BooleanField(default=False),
        ),
    ]
