# Generated by Django 5.0.6 on 2024-08-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_lecturer_is_hod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="syllabus",
                to="portal.department",
            ),
        ),
    ]
