# Generated by Django 5.0.6 on 2024-08-12 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_department_faculty_course_department_faculty_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="division",
                to="portal.faculty",
            ),
        ),
    ]
